- name: yum | add/remove package repos
  template:
    src: yum_repo.j2
    dest: /etc/yum.repos.d/{{ item.name }}.repo
    owner: root
    group: root
    mode: 0644
  with_items: '{{ packages_repos }}'

- name: yum | update cache
  yum:
    name: "*"
    update_cache: yes
  when: packages_update_cache

- name: yum | remove packages
  yum:
    name: "{{ item }}"
    state: absent
  with_items: '{{ packages_remove }}'

- name: yum | add packages from specific repos
  yum:
    name: "{{ item.name }}"
    state: present
    disablerepo: "*"
    enablerepo: "{{ item.repo }}"
  with_items: '{{ packages_add_specific_repo }}'

- name: yum | add packages from any repo
  yum:
    name: "{{ item }}"
    state: present
  with_items: '{{ packages_add }}'

# versionlock
- name: check if Yum versionlock plugin is installed
  yum:
    list="yum-versionlock"
  register: versionlock_is_installed

- name: Set versionlock on packages
  command: "yum versionlock {{ item }}"
  with_items: '{{ packages_versionlock }}'
  when:  (versionlock_is_installed.results|length == 1) or (versionlock_is_installed.results[1].yumstate != 'installed')
